### ISSUE TITLE
cogvideox_image_to_video_lora   Multi-card training Validation   appears " Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data."

### ISSUE THREAD

**Issue by glide-the** [a-r-r-o-w/cogvideox-factory#114]
### System Info 

nvidia-smi
Fri Dec  6 10:57:35 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

python 3.10

### Information 

- [X] The official example scripts  

### Reproduction  
bash train_image_to_video_lora_5b_tom.sh
```shell
#!/bin/bash 
export TORCH_LOGS="+dynamo,recompiles,graph_breaks"
# export TORCHDYNAMO_VERBOSE=1
export WANDB_MODE="online"
export NCCL_P2P_DISABLE=0
export NCCL_IB_DISABLE=1          # disable InfiniBand
export TORCH_NCCL_ENABLE_MONITORING=0
export WANDB_API_KEY=
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True 

GPU_IDS="1,2,3,4"

# Training Configurations
# Experiment with as many hyperparameters as you want!
LEARNING_RATES=("1e-3")
LR_SCHEDULES=("cosine_with_restarts")
OPTIMIZERS=("adamw")
MAX_TRAIN_STEPS=("12184")

# Single GPU uncompiled training
ACCELERATE_CONFIG_FILE="accelerate_configs/uncompiled_5b_lora.yaml"

# Absolute path to where the data is located. Make sure to have read the README for how to prepare data.
# This example assumes you downloaded an already prepared dataset from HF CLI as follows:
#   huggingface-cli download --repo-type dataset Wild-Heart/Disney-VideoGeneration-Dataset --local-dir /path/to/my/datasets/disney-dataset
DATA_ROOT="/mnt/ceph/develop/jiawei/lora_dataset/5B-Tom-and-Jerry-VideoGeneration-Dataset-encoded-image-to-video"
CAPTION_COLUMN="prompts.txt"
VIDEO_COLUMN="videos.txt"

# Launch experiments with different hyperparameters
for learning_rate in "${LEARNING_RATES[@]}"; do
  for lr_schedule in "${LR_SCHEDULES[@]}"; do
    for optimizer in "${OPTIMIZERS[@]}"; do
      for steps in "${MAX_TRAIN_STEPS[@]}"; do
        output_dir="/mnt/ceph/develop/jiawei/model_checkpoint/cogvideox-lora_i2v_5B-Tom-and-Jerry_optimizer_${optimizer}__steps_${steps}__lr-schedule_${lr_schedule}__learning-rate_${learning_rate}/"

        cmd="accelerate launch --config_file $ACCELERATE_CONFIG_FILE --main_process_port 29501 --gpu_ids $GPU_IDS training/cogvideox_image_to_video_lora.py \
          --pretrained_model_name_or_path /mnt/ceph/develop/jiawei/model_checkpoint/CogVideoX-5b-I2V \
          --data_root $DATA_ROOT \
          --caption_column $CAPTION_COLUMN \
          --video_column $VIDEO_COLUMN \
          --height_buckets 480 \
          --width_buckets 720 \
          --load_tensors \
          --frame_buckets 49 \
          --dataloader_num_workers 8 \
          --pin_memory \
          --validation_prompt \"Tom and Jerry, the iconic animated duo, are captured in a moment of playful chaos. Tom, the mischievous cat, is perched precariously on the edge of a large golden bowl filled with vibrant red apples and plump purple grapes. His eyes are focused, and his body language suggests he's plotting his next move. Meanwhile, Jerry, the agile mouse, scurries along the green floor, his tiny ears twitching as he senses Tom's presence. The scene is set against a backdrop of a richly decorated room with a blue door and a red curtain, adding to the opulence of the setting. The composition of the image, with Tom and Jerry in the foreground and the luxurious room in the background, creates a dynamic and engaging visual narrative.:::Tom, the mischievous gray cat, is seen standing on the edge of a round pool, his body partially submerged in the water. His eyes are focused on Jerry, the clever brown mouse, who is precariously perched on the edge of the pool, seemingly about to fall in. The scene is set against a backdrop of lush greenery, with the pool's blue water contrasting against the vibrant colors of the surroundings. The composition captures the tension between the two characters, as Tom's anticipation of catching Jerry is palpable.:::Tom, the mischievous gray cat, is captured in a moment of playful chaos on a wooden deck. He's dressed in a blue and white sailor outfit, complete with a white hat adorned with a red ribbon. His eyes are wide with excitement, and his mouth is open as if he's shouting or laughing. One of his paws is raised in the air, adding to the dynamic nature of the scene. The background features a clear blue sky and a calm sea, creating a stark contrast with Tom's energetic antics. The wooden planks of the deck stretch out behind him, leading the viewer's eye towards the horizon.\" \
          --validation_images \"/mnt/ceph/develop/jiawei/cogvideox-distillation/output/20241128_201157_frame0.jpg:::/mnt/ceph/develop/jiawei/cogvideox-distillation/output/20241128_201159_frame0.jpg:::/mnt/ceph/develop/jiawei/cogvideox-distillation/output/20241128_201200_frame0.jpg\"
          --validation_prompt_separator ::: \
          --num_validation_videos 3 \
          --validation_epochs 1 \
          --seed 42 \
          --rank 128 \
          --lora_alpha 64 \
          --mixed_precision bf16 \
          --output_dir $output_dir \
          --max_num_frames 49 \
          --train_batch_size 6 \
          --max_train_steps $steps \
          --checkpointing_steps 200 \
          --gradient_accumulation_steps 1 \
          --gradient_checkpointing \
          --learning_rate $learning_rate \
          --lr_scheduler $lr_schedule \
          --lr_warmup_steps 270 \
          --lr_num_cycles 1 \
          --noised_image_dropout 0.05 \
          --optimizer $optimizer \
          --beta1 0.9 \
          --beta2 0.95 \
          --weight_decay 0.001 \
          --max_grad_norm 1.0 \
          --allow_tf32 \
          --resume_from_checkpoint latest \
          --report_to wandb \
          --tracker_name cogvideox-lora_i2v_5B-Tom-and-Jerry_optimizer_${optimizer}__steps_${steps}__lr-schedule_${lr_schedule}__learning-rate_${learning_rate} \
          --nccl_timeout 1800"
        
        echo "Running command: $cmd"
        eval $cmd
        echo -ne "-------------------- Finished executing script --------------------\n\n"
      done
    done
  done
done

```

### Expected behavior  

I observed that other scripts did not do validation in "for step, batch in enumerate(train_dataloader):" should_run_validation
cogvideox_text_to_video_lora
cogvideox_text_to_video_sft

And in this code block, there will be multiple executions. Is it because there is no method like transformer.evel()?
@a-r-r-o-w @zr

error log

```

Steps:   2%| | 254/12184 [3:47:24<176:05:39, 53.14s/it, gradient_norm_after_clip=0.0115, gradient_norm_before_clip=0.011===== Memory before validation =====
memory_allocated=11.701 GB
max_memory_allocated=55.858 GB
max_memory_reserved=63.080 GB
                                                                                                                        Loaded tokenizer as T5Tokenizer from `tokenizer` subfolder of /mnt/ceph/develop/jiawei/model_checkpoint/CogVideoX-5b-I2V.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.02it/s]
Loaded text_encoder as T5EncoderModel from `text_encoder` subfolder of /mnt/ceph/develop/jiawei/model_checkpoint/CogVideoX-5b-I2V.eckpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.18it/s]
Loaded vae as AutoencoderKLCogVideoX from `vae` subfolder of /mnt/ceph/develop/jiawei/model_checkpoint/CogVideoX-5b-I2V.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████| 5/5 [00:00<00:00,  8.34it/s]
Validation image: /mnt/ceph/develop/jiawei/cogvideox-distillation/output/20241128_201157_frame0.jpg:00<00:00,  7.53it/s]
Validation prompt: Tom and Jerry, the iconic animated duo, are captured in a moment of playful chaos. Tom, the mischievous cat, is perched precariously on the edge of a large golden bowl filled with vibrant red apples and plump purple grapes. His eyes are focused, and his body language suggests he's plotting his next move. Meanwhile, Jerry, the agile mouse, scurries along the green floor, his tiny ears twitching as he senses Tom's presence. The scene is set against a backdrop of a richly decorated room with a blue door and a red curtain, adding to the opulence of the setting. The composition of the image, with Tom and Jerry in the foreground and the luxurious room in the background, creates a dynamic and engaging visual narrative.
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:50<00:00,  4.60s/it]
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:50<00:00,  4.60s/it]
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:49<00:00,  4.60s/it]
Validation image: /mnt/ceph/develop/jiawei/cogvideox-distillation/output/20241128_201159_frame0.jpg:49<00:00,  4.60s/it]
Validation prompt: Tom, the mischievous gray cat, is seen standing on the edge of a round pool, his body partially submerged in the water. His eyes are focused on Jerry, the clever brown mouse, who is precariously perched on the edge of the pool, seemingly about to fall in. The scene is set against a backdrop of lush greenery, with the pool's blue water contrasting against the vibrant colors of the surroundings. The composition captures the tension between the two characters, as Tom's anticipation of catching Jerry is palpable.
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:49<00:00,  4.60s/it]
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:50<00:00,  4.60s/it]
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:50<00:00,  4.60s/it]
Validation image: /mnt/ceph/develop/jiawei/cogvideox-distillation/output/20241128_201200_frame0.jpg:50<00:00,  4.61s/it]
Validation prompt: Tom, the mischievous gray cat, is captured in a moment of playful chaos on a wooden deck. He's dressed in a blue and white sailor outfit, complete with a white hat adorned with a red ribbon. His eyes are wide with excitement, and his mouth is open as if he's shouting or laughing. One of his paws is raised in the air, adding to the dynamic nature of the scene. The background features a clear blue sky and a calm sea, creating a stark contrast with Tom's energetic antics. The wooden planks of the deck stretch out behind him, leading the viewer's eye towards the horizon.
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:50<00:00,  4.60s/it]
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [03:50<00:00,  4.60s/it][rank1]:[E1205 04:35:53.538345302 ProcessGroupNCCL.cpp:607] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3348, OpType=BROADCAST, NumelIn=54607872, NumelOut=54607872, Timeout(ms)=1800000) ran for 1800049 milliseconds before timing out.
[rank1]:[E1205 04:35:53.538743134 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 3348, last enqueued NCCL work: 3348, last completed NCCL work: 3347.
[rank2]:[E1205 04:35:53.575550497 ProcessGroupNCCL.cpp:607] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3348, OpType=BROADCAST, NumelIn=54607872, NumelOut=54607872, Timeout(ms)=1800000) ran for 1800089 milliseconds before timing out.
[rank2]:[E1205 04:35:53.575788449 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 2] Exception (either an error or timeout) detected by watchdog at work: 3348, last enqueued NCCL work: 3348, last completed NCCL work: 3347.
[rank3]:[E1205 04:35:53.584483882 ProcessGroupNCCL.cpp:607] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3348, OpType=BROADCAST, NumelIn=54607872, NumelOut=54607872, Timeout(ms)=1800000) ran for 1800098 milliseconds before timing out.
[rank3]:[E1205 04:35:53.584921826 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 3] Exception (either an error or timeout) detected by watchdog at work: 3348, last enqueued NCCL work: 3348, last completed NCCL work: 3347.
                                                                                                                        [rank3]:[E1205 04:35:57.185951768 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 3] Timeout at NCCL work: 3348, last enqueued NCCL work: 3348, last completed NCCL work: 3347.
[rank3]:[E1205 04:35:57.185975464 ProcessGroupNCCL.cpp:621] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E1205 04:35:57.185981586 ProcessGroupNCCL.cpp:627] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E1205 04:35:57.187332418 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3348, OpType=BROADCAST, NumelIn=54607872, NumelOut=54607872, Timeout(ms)=1800000) ran for 1800098 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f62842cbf86 in /mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f62365ca8f2 in /mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7f62365d1333 in /mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f62365d371c in /mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7f62884aabf4 in /mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/../../libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7f6289775ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x7f6289807850 in /lib/x86_64-linux-gnu/libc.so.6)

W1205 04:35:57.592000 140562404357952 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 654580 closing signal SIGTERM
W1205 04:35:57.593000 140562404357952 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 654581 closing signal SIGTERM
W1205 04:35:57.594000 140562404357952 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 654582 closing signal SIGTERM
E1205 04:35:59.439000 140562404357952 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 3 (pid: 654583) of binary: /mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/bin/python
Traceback (most recent call last):
  File "/mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/ceph/develop/jiawei/conda_env/cogvidex_distillation/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=======================================================
training/cogvideox_image_to_video_lora.py FAILED

```

**Comment by glide-the** [comment]
But when I use a num_validation_videos, this problem does not occur again

![image](https://github.com/user-attachments/assets/b999499c-0f63-4d5d-81fc-bd7247d56dd8)

**Comment by a-r-r-o-w** [comment]
This looks like an error caused due to excessive time spent in validation. This happens usually because the currently scripts don't have multi-GPU validation. This causes one GPU to run validation, while all other GPUs are stalled with no work. This makes NCCL believe that there is a communication failure from the validation GPU to all other GPUs, which causes the error.

You are setting nccl_timeout to 1800 seconds. Typically, one video generation takes about 270 seconds. In 1800 seconds, you can do about ~7 videos, but you're trying to generate more than that, so it causes the communcation failure mentioned above.

I will add multi-GPU validation support in the future so that they don't wait idly. For now, one has to reduce validation videos, or increase NCCL timeout

**Comment by glide-the** [comment]
> This looks like an error caused due to excessive time spent in validation. This happens usually because the currently scripts don't have multi-GPU validation. This causes one GPU to run validation, while all other GPUs are stalled with no work. This makes NCCL believe that there is a communication failure from the validation GPU to all other GPUs, which causes the error.
> 
> 
> 
> You are setting nccl_timeout to 1800 seconds. Typically, one video generation takes about 270 seconds. In 1800 seconds, you can do about ~7 videos, but you're trying to generate more than that, so it causes the communcation failure mentioned above.
> 
> 
> 
> I will add multi-GPU validation support in the future so that they don't wait idly. For now, one has to reduce validation videos, or increase NCCL timeout

I will try out the 1800-second timeout parameter soon. Thank you very much for the suggestion!
