### ISSUE TITLE
AttributeError: type object 'CogVideoXImageToVideoPipeline' has no attribute 'save_lora_weights'

### ISSUE THREAD

**Issue by Cubey42** [a-r-r-o-w/cogvideox-factory#58]
```Steps: 100%|█| 500/500 [1:34:25<00:00, 10.94s/it, gradient_norm_after_clip=0, gradient_norm_before_clip=0, lTraceback (most recent call last):
  File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 967, in <module>
    main(args)
  File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 876, in main
    CogVideoXImageToVideoPipeline.save_lora_weights(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CogVideoXImageToVideoPipeline' has no attribute 'save_lora_weights'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 967, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 876, in main
[rank0]:     CogVideoXImageToVideoPipeline.save_lora_weights(
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: AttributeError: type object 'CogVideoXImageToVideoPipeline' has no attribute 'save_lora_weights'
```
I kept getting this with tests, when I did a long run it looked like this when checkpointing
```Steps:  25%|▎| 500/2000 [1:31:37<4:40:46, 11.23s/it, gradient_norm_after_clip=0, gradient_norm_before_clip=0[2024-10-20 13:27:02,056] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint pytorch_model is about to be saved!
[2024-10-20 13:27:18,842] [INFO] [logging.py:96:log_dist] [Rank 0] Saving model checkpoint: ./resultstenti2v/cogvideox-lora/checkpoint-500/pytorch_model/mp_rank_00_model_states.pt
[2024-10-20 13:27:18,842] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving ./resultstenti2v/cogvideox-lora/checkpoint-500/pytorch_model/mp_rank_00_model_states.pt...
[2024-10-20 13:27:59,017] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved ./resultstenti2v/cogvideox-lora/checkpoint-500/pytorch_model/mp_rank_00_model_states.pt.
[2024-10-20 13:27:59,097] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving ./resultstenti2v/cogvideox-lora/checkpoint-500/pytorch_model/bf16_zero_pp_rank_0_mp_rank_00_optim_states.pt...
[2024-10-20 13:27:59,961] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved ./resultstenti2v/cogvideox-lora/checkpoint-500/pytorch_model/bf16_zero_pp_rank_0_mp_rank_00_optim_states.pt.
[2024-10-20 13:27:59,962] [INFO] [engine.py:3536:_save_zero_checkpoint] zero checkpoint saved ./resultstenti2v/cogvideox-lora/checkpoint-500/pytorch_model/bf16_zero_pp_rank_0_mp_rank_00_optim_states.pt
[2024-10-20 13:27:59,962] [INFO] [torch_checkpoint_engine.py:33:commit] [Torch] Checkpoint pytorch_model is ready now!
Traceback (most recent call last):
  File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 967, in <module>
    main(args)
  File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 794, in main
    accelerator.save_state(save_path)
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/accelerate/accelerator.py", line 3081, in save_state
    hook(self._models, weights, output_dir)
  File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 391, in save_model_hook
    raise ValueError(f"unexpected save model: {model.__class__}")
ValueError: unexpected save model: <class 'deepspeed.runtime.engine.DeepSpeedEngine'>```

**Comment by a-r-r-o-w** [comment]
Need to install diffusers from the `main` branch for the CogVideoXImageToVideoPipeline to be able to load/save lora weights. DeepSpeed related fixes were made in #38, so be sure to pull latest changes. Also completed a full training run [here](https://github.com/a-r-r-o-w/cogvideox-factory/pull/38#issuecomment-2422445879), so not sure why you see the DeepSpeed error

**Comment by Cubey42** [comment]
> Need to install diffusers from the `main` branch for the CogVideoXImageToVideoPipeline to be able to load/save lora weights. DeepSpeed related fixes were made in #38, so be sure to pull latest changes. Also completed a full training run [here](https://github.com/a-r-r-o-w/cogvideox-factory/pull/38#issuecomment-2422445879), so not sure why you see the DeepSpeed error

I am now on latest pull and using the provided prepare_dataset.py with --use_tiling, --save_image_latents, --save_latents_and_embeddings 
I'm now getting this ```memory_allocated=20.011 GB
max_memory_allocated=20.011 GB
max_memory_reserved=20.027 GB
***** Running training *****
  Num trainable parameters = 132120576
  Num examples = 59
  Num batches each epoch = 59
  Num epochs = 1
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient accumulation steps = 1
  Total optimization steps = 10
Steps:   0%|                                                                         | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 978, in <module>
    main(args)
  File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 652, in main
    for step, batch in enumerate(train_dataloader):
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/accelerate/data_loader.py", line 547, in __iter__
    dataloader_iter = self.base_dataloader.__iter__()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 440, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1083, in __init__
    self._reset(loader, first_iter=True)
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1116, in _reset
    self._try_put_index()
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1350, in _try_put_index
    index = self._next_index()
            ^^^^^^^^^^^^^^^^^^
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/sampler.py", line 288, in __iter__
    for idx in self.sampler:
  File "/home/cubeyai/cogvideox-factory/training/dataset.py", line 410, in __iter__
    self.buckets[(f, h, w)].append(data)
    ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: (49, 720, 960)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 978, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/cubeyai/cogvideox-factory/training/cogvideox_image_to_video_lora.py", line 652, in main
[rank0]:     for step, batch in enumerate(train_dataloader):
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/accelerate/data_loader.py", line 547, in __iter__
[rank0]:     dataloader_iter = self.base_dataloader.__iter__()
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 440, in __iter__
[rank0]:     return self._get_iterator()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
[rank0]:     return _MultiProcessingDataLoaderIter(self)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1083, in __init__
[rank0]:     self._reset(loader, first_iter=True)
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1116, in _reset
[rank0]:     self._try_put_index()
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1350, in _try_put_index
[rank0]:     index = self._next_index()
[rank0]:             ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
[rank0]:     return next(self._sampler_iter)  # may raise StopIteration
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/cogvideox-factory/vvv/lib/python3.12/site-packages/torch/utils/data/sampler.py", line 288, in __iter__
[rank0]:     for idx in self.sampler:
[rank0]:   File "/home/cubeyai/cogvideox-factory/training/dataset.py", line 410, in __iter__
[rank0]:     self.buckets[(f, h, w)].append(data)
[rank0]:     ~~~~~~~~~~~~^^^^^^^^^^^
[rank0]: KeyError: (49, 720, 960)```

**Comment by a-r-r-o-w** [comment]
This is because the bucket sampler initializes its internal dictionary using the values provided in `--height_buckets`, `--width_buckets` and `--frame_buckets`. If you've run `prepare_dataset.py` at `49 x 720 x 960` resolution, please make sure to pass the same buckets configuration to the training scripts too. Maybe will make this clearer in the README soon

**Comment by Cubey42** [comment]
Is now working, thank you. is training at 720x960 lead to better quality?
