### ISSUE TITLE
Bucketing question

### ISSUE THREAD

**Issue by cseti007** [a-r-r-o-w/cogvideox-factory#78]
First of all thank you for your great work! 
I have a dataset contains 106 videos with different frame counts, like 16, 17, 24, 25, 32, 40, 41, 48, 49
When I set the frame buckets in the script like this: --frame_buckets 16 17 24 25 32 33 40 41 48 49 \
The script starts properly but after around 80 steps I get an error message:

Steps:   2%|█▎                                                                                | 81/5000 [18:24<20:12:25, 14.79s/it, gradient_norm_after_clip=0.0135, gradient_norm_before_clip=0.0135, loss=0.149, lr=2.03e-5]Traceback (most recent call last):
  File "/workspace/cogvideox-factory/training/cogvideox_text_to_video_lora.py", line 945, in <module>
    main(args)
  File "/workspace/cogvideox-factory/training/cogvideox_text_to_video_lora.py", line 644, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.11/dist-packages/accelerate/data_loader.py", line 563, in __iter__
    next_batch = next(dataloader_iter)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 1368, in _process_data
    self._try_put_index()
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 1350, in _try_put_index
    index = self._next_index()
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/data/sampler.py", line 288, in __iter__
    for idx in self.sampler:
  File "/workspace/cogvideox-factory/training/dataset.py", line 406, in __iter__
    for index, data in enumerate(self.data_source):
  File "/workspace/cogvideox-factory/training/dataset.py", line 146, in __getitem__
    image, video, _ = self._preprocess_video(self.video_paths[index])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/cogvideox-factory/training/dataset.py", line 283, in _preprocess_video
    frame_indices = list(range(0, video_num_frames, video_num_frames // nearest_frame_bucket))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: range() arg 3 must not be zero

Can you help me out? Does my understanding wrong about bucketing?

**Comment by cseti007** [comment]
Found the problem. One of my videos had wrong frame length.
