### ISSUE TITLE
4090 run prepare_dataset.sh oom

### ISSUE THREAD

**Issue by syyxsxx** [a-r-r-o-w/cogvideox-factory#79]
### System Info / 系統信息

gpu: 4090 24gb

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

hi i use 4090 run prepare_dataset.sh, but got oom. May I ask if it is possible to prepare data on 4090
```
An exception occurred while processing data: rank=0, world_size=1, step=1
Traceback (most recent call last):
  File "/workspace/cogvideox-factory/training/prepare_dataset.py", line 535, in main
    video_latents = vae._encode(videos)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 1195, in _encode
    x_intermediate, conv_cache = self.encoder(x_intermediate, conv_cache=conv_cache)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 799, in forward
    hidden_states, new_conv_cache[conv_cache_key] = down_block(
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 431, in forward
    hidden_states, new_conv_cache[conv_cache_key] = resnet(
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 296, in forward
    hidden_states, new_conv_cache["conv1"] = self.conv1(hidden_states, conv_cache=conv_cache.get("conv1"))
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 134, in forward
    inputs = F.pad(inputs, padding_2d, mode="constant", value=0)
  File "/root/miniconda3/envs/cog/lib/python3.10/site-packages/torch/nn/functional.py", line 4552, in pad
    return torch._C._nn.pad(input, pad, mode, value)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.17 GiB. GPU 0 has a total capacity of 23.55 GiB of which 243.75 MiB is free. Including non-PyTorch memory, this process has 23.30 GiB memory in use. Of the allocated memory 21.96 GiB is allocated by PyTorch, and 918.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Expected behavior / 期待表现

能解决问题

**Comment by syyxsxx** [comment]
set the datatype to fp16 slove the issue
